# Generated by Django 5.0.4 on 2024-04-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=64)),
                ('contact', models.CharField(max_length=64)),
                ('joining_date', models.DateField()),
                ('salary', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('SAP', 'SAP'), ('FullStack Developer', 'FullStack Developer'), ('SAP_FICO', 'SAP_FICO'), ('Sales', 'Sales')], max_length=20)),
                ('position', models.CharField(choices=[('Trainee', 'Trainee'), ('Associate', 'Associate'), ('Consultant', 'Consultant'), ('Senior Associate', 'Senior Associate'), ('Manager', 'Manager')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
