# Generated by Django 5.0.4 on 2024-04-20 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_code', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Paid Leave', 'Piad Leave'), ('Others', 'Others')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Approved'), ('2', 'Rejected'), ('3', 'Registered'), ('4', 'Cancelled')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_profiles.profile')),
            ],
        ),
    ]
