# Generated by Django 5.0.4 on 2024-04-20 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_profiles', '0002_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=64)),
                ('project_type', models.CharField(choices=[('1', 'Support'), ('2', 'Implementation')], max_length=64)),
                ('start_date', models.DateField()),
                ('end_time', models.DateField()),
                ('completed', models.BooleanField()),
                ('project_description', models.TextField()),
                ('execution_type', models.CharField(choices=[('1', 'Onsite'), ('2', 'Offsite')], default=None, max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profiles.profile')),
            ],
        ),
    ]
