# Generated by Django 5.0.4 on 2024-04-24 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_profiles', '0003_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetype', models.CharField(choices=[('1', 'Hardware'), ('2', 'Software')], max_length=64)),
                ('manufacturer', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('asset', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Registered'), ('2', 'Assigned'), ('3', 'Resolved'), ('4', 'Completed'), ('5', 'Replaced')], max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_profiles.profile')),
            ],
        ),
    ]
